### ISSUE TITLE
fcgi flags compatible changes to

### ISSUE THREAD

**Issue by yuzujoe** [alash3al/http2fcgi#5]
I understand that many of the following changes are destructive, but if I was using -fcgi, how do I change it?

https://github.com/alash3al/phoo/commit/8f2a38e11bed732d51669b5f39e6e471b5da9b51

```
{"time":"2023-10-26T11:44:18.517843451Z","level":"ERROR","prefix":"-","file":"main.go","line":"32","message":"flag provided but not defined: -fcgi"}
Waiting phoo ready...
Incorrect Usage: flag provided but not defined: -fcgi
```

**Comment by alash3al** [comment]
@yuzujoe 

`phoo` now focuses on PHP especially laravel & symfony, if you did `phoo serve --help` you will find the options there.

**P.S** `phoo` will automatically spawn `php-fpm` for you, you don't have to set the `fpm` server address, all what you need is `--fpm=php-fpm8.2` if there is no binary in your system called `php-fpm` but called `php-fpm8.2`

**Comment by yuzujoe** [comment]
Here's how it's set up now.
```
phoo --fcgi tcp://localhost:9000 \
               --http localhost:8002 \
               --root /workspace/public
```

I don't know how this is mapped to the following flags, etc.
https://github.com/alash3al/phoo/blob/master/cmd/serve/flags.go
